name: CI

on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v1
      name: Setup node.js and yarn
      with:
        node-version: 13.1.0

    - name: Get yarn cache directory
      id: yarn-cache-get-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      name: Restore yarn cache
      with:
        path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn install
      run: yarn install --frozen-lockfile

    - uses: actions/cache@v1
      id: typescript-cache
      name: Restore TypeScript cache
      with:
        path: .sewing-kit/cache/typescript/
        key: ${{ runner.os }}-typescript
        restore-keys: |
          ${{ runner.os }}-typescript

    - name: Type check
      run: yarn type-check

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v1
      name: Setup node.js and yarn
      with:
        node-version: 13.1.0

    - name: Get yarn cache directory
      id: yarn-cache-get-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      name: Restore yarn cache
      with:
        path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn install
      run: yarn install --frozen-lockfile

    - uses: actions/cache@v1
      id: jest-cache
      name: Restore jest cache
      with:
        path: .sewing-kit/cache/jest/
        key: ${{ runner.os }}-jest
        restore-keys: |
          ${{ runner.os }}-jest

    - name: Test
      run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v1
      name: Setup node.js and yarn
      with:
        node-version: 13.1.0

    - name: Get yarn cache directory
      id: yarn-cache-get-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      name: Restore yarn cache
      with:
        path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn install
      run: yarn install --frozen-lockfile

    - uses: actions/cache@v1
      id: eslint-cache
      name: Restore ESLint cache
      with:
        path: .sewing-kit/cache/eslint
        key: ${{ runner.os }}-eslint
        restore-keys: |
          ${{ runner.os }}-eslint

    - name: Lint
      run: yarn lint
